---
# maintains file name, binary names, and anything which is not a directory or path

# config file names
node_config_file_name: config.yaml

# binary names
node_service_default_binary_name: genlayernode

# environment file names
node_environment_secret_file_name: "{{ service_identifier }}.secrets.env"

node_operator_key_file_name: operator.json
