---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ manager_home_dir }}"
    directories: "{{ manager_directories }}"
    log_file_path: "{{ manager_log_file_path }}"

- name: Include extract binaries task
  ansible.builtin.include_tasks: extract_binaries.yml

- name: Copy genvm manager configuration file
  ansible.builtin.template:
    src: "{{ env }}/genvm_manager.yaml.j2"
    dest: "{{ manager_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
