---
- name: Create a temporary directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive
  vars:
    archive_name: "genlayer-node-linux-amd64-{{ genlayer.validator.version }}.tar.gz"
    prefix_url: "{{ system_architecture }}/{{ genlayer.validator.version }}/{{ archive_name }}"
  ansible.builtin.unarchive:
    src: "{{ genlayer.source_url }}/{{ prefix_url }}"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root

- name: Copy the binary file
  vars:
    binary_subpath: "genlayer-node-linux-amd64/bin"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/{{ binary_subpath }}/{{ node_service_default_binary_name }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Copy the genvm related folder
  vars:
    binary_subpath: "genlayer-node-linux-amd64"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/{{ binary_subpath }}/third_party"
    dest: "{{ node_home_dir }}"
    remote_src: true
    owner: "{{ service_identifier }}"
    group: "{{ project }}"
    force: true
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent

- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - python3-venv

- name: Run GenVM setup script to patch runners
  ansible.builtin.command: python3 ./third_party/genvm/bin/setup.py
  args:
    chdir: "{{ node_home_dir }}"
  register: genvm_setup_result
  changed_when: genvm_setup_result.rc == 0
  when: setup_genvm | default(false) | bool
