---
- name: Include the ufw vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Include extract binaries task
  ansible.builtin.include_tasks: extract_binaries.yml

- name: Copy node configuration file
  ansible.builtin.template:
    src: "{{ env }}/config.yaml.j2"
    dest: "{{ node_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ project }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_vault_secrets | default(false) | bool
  block:
    - name: Fetch secret environment file
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ env }}/{{ type }}/{{ node_environment_secret_file_name }}"
        secret_destination_path: "{{ node_environment_secret_file_path }}"
        secret_type: environment

    - name: Fetch operator key file
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ env }}/{{ type }}/{{ node_operator_key_file_name }}"
        secret_destination_path: "{{ node_operator_key_file_path }}"
        secret_type: json

    - name: Import GenLayer operator account keystore
      ansible.builtin.command:
        cmd: >
          {{ node_bin_dir }}/{{ service_identifier }} account import 
          --password "{{ lookup('env', 'OPERATOR_ACCOUNT_PASSWORD') }}" 
          --passphrase "{{ lookup('env', 'OPERATOR_ACCOUNT_PASSWORD') }}" 
          --path "{{ node_operator_key_file_path }}" 
          -c "{{ node_config_file_path }}" 
          --setup
        chdir: "{{ node_home_dir }}"
      no_log: true
      notify:
        - Restart service

    - name: Set ownership for data directory
      ansible.builtin.file:
        path: "{{ node_data_dir }}"
        owner: "{{ service_identifier }}"
        group: "{{ project }}"
        recurse: true

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
